--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9
-- Dumped by pg_dump version 16.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: banknote; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.banknote (
    denominator integer NOT NULL,
    count integer NOT NULL,
    CONSTRAINT banknote_count_check CHECK ((count >= 0)),
    CONSTRAINT banknote_denominator_check CHECK ((denominator > 0))
);


--
-- Name: card; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.card (
    card_number character varying(13) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    pin_hash text NOT NULL,
    balance numeric(12,2) DEFAULT 0.00 NOT NULL,
    credit_limit numeric(12,2) DEFAULT 0.00 NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    from_card character varying(19),
    to_card character varying(19),
    type character varying(16) NOT NULL,
    amount numeric(14,2) NOT NULL,
    status character varying(16) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT transactions_amount_check CHECK ((amount > (0)::numeric))
);


--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: transactions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.transactions_id_seq OWNED BY public.transactions.id;


--
-- Name: transactions_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: banknote; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.banknote (denominator, count) FROM stdin;
10	200
100	1000
\.


--
-- Data for Name: card; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.card (card_number, first_name, last_name, pin_hash, balance, credit_limit, created_at, updated_at) FROM stdin;
1234567890987	Billy	Jean	$2a$12$XkkhSlP9gKWQHRi1mU25n.kww3RBF.s81XG3uWxwQ8kLbo2r4l.dW	1750.00	0.00	2025-11-09 21:11:17.75092	2025-11-09 21:11:17.75092
1234567890123	Test	Testyuck	$2a$12$XkkhSlP9gKWQHRi1mU25n.kww3RBF.s81XG3uWxwQ8kLbo2r4l.dW	-200.00	500.00	2025-11-09 11:16:13.06472	2025-11-09 11:16:13.06472
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.transactions (id, from_card, to_card, type, amount, status, created_at) FROM stdin;
1	1234567890123456	9876543210987654	TRANSFER	120.00	FAILED	2025-11-09 22:58:35.714066+02
2	1234567890123456	9876543210987654	TRANSFER	120.00	FAILED	2025-11-09 23:19:39.095034+02
3	1234567890123456	9876543210987654	TRANSFER	120.00	FAILED	2025-11-09 23:23:37.169117+02
4	1234567890123	1234567890123	DEPOSIT	200.00	SUCCESSFUL	2025-11-15 10:06:48.720702+02
\.


--
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.transactions_id_seq', 1, false);


--
-- Name: transactions_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.transactions_id_seq1', 4, true);


--
-- Name: card card_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card
    ADD CONSTRAINT card_pkey PRIMARY KEY (card_number);


--
-- Name: card card_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card
    ADD CONSTRAINT card_unique UNIQUE (card_number);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

